# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
  armhf: "ghcr.io/home-assistant/armhf-base:3.15"
  armv7: "ghcr.io/home-assistant/armv7-base:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Siemens PLC communication"
  org.opencontainers.image.description: "This addon communicates with a Siemens PLC, S7 or a logo. "
  org.opencontainers.image.source: "https://github.com/dixi83/hass-siemens-plc-addon"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
