---
# yamllint disable rule:line-length
name: ModBus Measurement Daemon
version: 0.0.2
slug: ha-mbmd
description: "A daemon for collecting measurement data from smart meters and grid inverters over modbus."
url: https://github.com/dixi83/hassio-addons/ha-mbmd
init: false
arch:
  - amd64
map:
  - addon_config:rw
options:
  log_level: warning
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
