---
name: MQTT Siemens S7 Connector
version: 0.1.1
slug: mqtt-s7-connector
description: "MQTT Siemens S7 connector to integrate Siemens PLC's with Home Assistant"
url: https://github.com/dixi83/hassio-addons/mqtt-s7-connector
init: false
services:
  - mqtt:need
discovery:
  - mqtt
arch:
  - aarch64
  - amd64
map:
  - addon_config:rw
options:
  log_level: info
  config_file: config.yaml
  config_files: 
    - config_plc1.yaml
    - config_plc2.yaml
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  config_file: str?
  config_files: 
    - str?
